"""empty message

Revision ID: 763626874e69
Revises: fede2242e457
Create Date: 2022-03-29 20:18:53.879662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763626874e69'
down_revision = 'fede2242e457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('sysdate'), nullable=True))
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
