"""empty message

Revision ID: fede2242e457
Revises: 0021c0f47ddf
Create Date: 2022-03-21 05:04:06.746144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fede2242e457'
down_revision = '0021c0f47ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastname', sa.String(length=120), nullable=True))
    op.drop_constraint('users_name_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_name_key', 'users', ['name'])
    op.drop_column('users', 'lastname')
    # ### end Alembic commands ###
